apiVersion: apps/v1
kind: Deployment

metadata:
  name: checkout

  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-app

spec:

{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/instance: checkout
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: retail-store-app

  template:

    metadata:

      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"

      labels:
        app.kubernetes.io/name: checkout
        app.kubernetes.io/instance: checkout
        app.kubernetes.io/component: service
        app.kubernetes.io/owner: retail-store-app

    spec:

      topologySpreadConstraints:

        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: checkout
              app.kubernetes.io/component: service
              app.kubernetes.io/instance: checkout

        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: checkout
              app.kubernetes.io/component: service
              app.kubernetes.io/instance: checkout

      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        fsGroup: 1000

      containers:

        - name: checkout

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: checkout

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000

          ports:
            - name: http
              containerPort: {{ .Values.checkout.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.checkout.probes.readiness.path }}
              port: {{ .Values.checkout.containerPort }}

            initialDelaySeconds: {{ .Values.checkout.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.checkout.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.checkout.probes.liveness.path }}
              port: {{ .Values.checkout.containerPort }}

            initialDelaySeconds: {{ .Values.checkout.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.checkout.probes.liveness.periodSeconds }}

          resources:
{{ toYaml .Values.checkout.resources | indent 12 }}

          volumeMounts:

            - mountPath: /tmp
              name: tmp-volume

      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory