apiVersion: apps/v1
kind: Deployment

metadata:
  name: orders

  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-app

spec:

{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/instance: orders
      app.kubernetes.io/component: service
      app.kubernetes.io/owner: retail-store-app

  template:

    metadata:

      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"

      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/instance: orders
        app.kubernetes.io/component: service
        app.kubernetes.io/owner: retail-store-app

    spec:

      topologySpreadConstraints:

        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: orders
              app.kubernetes.io/component: service
              app.kubernetes.io/instance: orders

        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: orders
              app.kubernetes.io/component: service
              app.kubernetes.io/instance: orders

      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        fsGroup: 1000

      containers:

        - name: orders

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: orders

            - secretRef:
                name: orders-db

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000

          ports:
            - name: http
              containerPort: {{ .Values.orders.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.orders.probes.readiness.path }}
              port: {{ .Values.orders.containerPort }}

            initialDelaySeconds: {{ .Values.orders.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.orders.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.orders.probes.liveness.path }}
              port: {{ .Values.orders.containerPort }}

            initialDelaySeconds: {{ .Values.orders.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.orders.probes.liveness.periodSeconds }}

          resources:
{{ toYaml .Values.orders.resources | indent 12 }}

          volumeMounts:

            - mountPath: /tmp
              name: tmp-volume

            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true

      volumes:

        - name: tmp-volume
          emptyDir:
            medium: Memory

        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.secrets.secretProviderClass }}"