# Source: retail-store-app-orders-chart/templates/rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orders-rabbitmq
  labels:
    app: retail-store-app
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: tcp-amqp
    - port: 15672
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: orders-rabbitmq