# =========================================================
# Retail Store - UI Service values.yaml
# =========================================================

# ---------------------------------------------------------
# UI Application
# ---------------------------------------------------------
image:
  repository: tcollins520/retail-store-ui
  pullPolicy: IfNotPresent
  tag: 2.0.0

ui:

  replicas: 2

  containerPort: 8080

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  resources:
    requests:
      cpu: 50m
      memory: 128Mi

    limits:
      cpu: 200m
      memory: 256Mi

  probes:
    readiness:
      path: /actuator/health/readiness
      initialDelaySeconds: 10
      periodSeconds: 5

    liveness:
      path: /actuator/health/readiness
      initialDelaySeconds: 30
      periodSeconds: 10


# ---------------------------------------------------------
# ConfigMap Values
# ---------------------------------------------------------
config:
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog
  RETAIL_UI_ENDPOINTS_CARTS: http://carts
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders


# ---------------------------------------------------------
# Ingress
# ---------------------------------------------------------
ingress:

  enabled: true

  className: nginx

  host: ui.tcapp.xyz

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

  tls:
    enabled: false


# ---------------------------------------------------------
# Image Pull Secrets
# ---------------------------------------------------------
imagePullSecrets: []


# ---------------------------------------------------------
# Service Account
# ---------------------------------------------------------
serviceAccount:

  create: true

  name: ui


# ---------------------------------------------------------
# Autoscaling
# ---------------------------------------------------------
autoscaling:

  enabled: false

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 70


# ---------------------------------------------------------
# Init Containers
# ---------------------------------------------------------
initContainers:

  enabled: true

  image: busybox:1.36


# ---------------------------------------------------------
# Global Service Values
# ---------------------------------------------------------
service:
  type: ClusterIP
  port: 80