apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: catalog-mysql

spec:
  serviceName: catalog-mysql

  replicas: 1

  selector:
    matchLabels:
      app: catalog-mysql

  template:
    metadata:
      labels:
        app: catalog-mysql

    spec:
      containers:
        - name: mysql

          image: "public.ecr.aws/docker/library/mysql:8.0"

          imagePullPolicy: IfNotPresent

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-secret-pw

            - name: MYSQL_DATABASE
              value: catalog

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: RETAIL_CATALOG_PERSISTENCE_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: RETAIL_CATALOG_PERSISTENCE_PASSWORD

          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: gp2

        resources:
          requests:
            storage: 5Gi