# Source: retail-store-app-orders-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: {{ .Values.orders.replicas }}

  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders

    spec:
      serviceAccountName: orders

      initContainers:
        - name: wait-for-postgresql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z orders-postgresql 5432;
              do
                echo "Waiting for PostgreSQL ..."
                sleep 2
              done

        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z orders-rabbitmq 5672;
              do
                echo "Waiting for RabbitMQ..."
                sleep 2
              done

      securityContext:
        fsGroup: 1000
        
      containers:
        - name: orders
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom

          envFrom:
            - secretRef:
                name: orders-rabbitmq
            - secretRef:
                name: orders-db
            - configMapRef:
                name: orders

          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.orders.containerPort }}
              protocol: TCP
              
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory