apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
data:
  RETAIL_catalog_PERSISTENCE_PROVIDER: postgres
  RETAIL_catalog_PERSISTENCE_ENDPOINT: catalog-postgres-db.cml0yuu2ka2y.us-east-1.rds.amazonaws.com:5432
  RETAIL_catalog_PERSISTENCE_NAME: catalogdb
  RETAIL_catalog_MESSAGING_PROVIDER: sqs
  RETAIL_catalog_MESSAGING_SQS_TOPIC: retail-dev-catalog-queue
  #RETAIL_catalog_MESSAGING_SQS_TOPIC: https://sqs.us-east-1.amazonaws.com/180789647333/retail-dev-catalog-queue
