# Source: retail-store-app-cart-chart/templates/dynamodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-dynamodb

spec:
  replicas: {{ .Values.dynamodb.replicas }}

  selector:
    matchLabels:
      app: carts-dynamodb

  template:
    metadata:
      labels:
        app: carts-dynamodb
    spec:
      containers:
        - name: carts-dynamodb
          image: "{{ .Values.dynamodb.image.repository }}:{{ .Values.dynamodb.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: carts-dynamodb
              containerPort: 8000
              protocol: TCP
