# Source: retail-store-app-cart-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    app: carts
spec:
  replicas: {{ .Values.cart.replicas }}

  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app: carts

  template:
    metadata:
      labels:
        app: carts
    spec:
      serviceAccountName: carts

      initContainers:
        - name: wait-for-dynamodb

          image: busybox:1.36

          command:
            - sh
            - -c
            - |
              until nc -z carts-dynamodb 8000;
              do
                echo "Waiting for DynamoDB..."
                sleep 2
              done
      containers:
        - name: carts
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - configMapRef:
                name: carts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.cart.containerPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

          resources:
            requests:
              cpu: 50m
              memory: 128Mi

            limits:
              cpu: 200m
              memory: 256Mi

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true    
              
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume

      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory